### ISSUE TITLE
Discussion about including the histology atlas in PAM50 upon installation

### ISSUE THREAD

**Issue by jcohenadad** [spinalcordtoolbox/PAM50#7]
Spin-off of [this comment](https://github.com/spinalcordtoolbox/PAM50/pull/6#issuecomment-1465049448): 

>> (from internal discussion): Might not need to be included in the mainline PAM50 template – could be a separate sct_download_data download.

> It will be necessary not only to update the URL but also to add a new option to [download.py](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/download.py). Something like PAM50_histology?

I _think_ it would be nice to include the histology atlas upon installation, if it is not "too" large. And i think we should be able to reduce it to 50MB (currently 92MB).

**Comment by jcohenadad** [comment]
> What's the size of all these files? (related to #7)

After resampling all files to `0.083333, 0.083333, 0.5`, the total size is 179M:

```console
valosek@macbook-pro:~/code/PAM50/histology$ du -h      
179M	.
```

i.e., a dramatic increase from [current 92M](https://github.com/spinalcordtoolbox/PAM50/issues/7#issue-1621490978):

```console
valosek@macbook-pro:~/code/PAM50/histology_backup$ du -h
 92M	.
```

I tried to change `gzip` compression ratio from default 6 to 9 ("slowest compression level, which provides the smallest file size"), but the size decrease is negligible:

```console
valosek@macbook-pro:~/code/PAM50/histology$ du -h
177M	.
```

I also tried `bzip2`; the compression performance is similar.

We can try to play with the data type, which is currently float32.

**Comment by jcohenadad** [comment]
Alternatively, we change the resampling to 200 µm x 200 µm x 500 µm. I think it should be "good enough" for what our users will do with the data (ie: compare with MRI)

**Comment by valosekj** [comment]
> Alternatively, we change the resampling to 200 µm x 200 µm x 500 µm. I think it should be "good enough" for what our users will do with the data (ie: compare with MRI)

This sounds good!

I used:

```console
valosek@macbook-pro:~/code/PAM50/histology_200x200x500um$ for file in *nii.gz;do;sct_resample -i ${file} -mm 0.2x0.2x0.5 -x linear;done
```

Then, `dim` is `[3, 108, 83, 205, 1, 1, 1, 1]` and `pixdim` is `[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]`:

```console
valosek@macbook-pro:~/code/PAM50/histology_200x200x500um$ for file in *.gz;do echo ${file};sct_image -i ${file} -header | grep dim | head -3;echo "";done
PAM50_200um_AVF.nii.gz
dim		[3, 108, 83, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]

PAM50_200um_Eccentricity.nii.gz
dim		[3, 108, 83, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]

PAM50_200um_EquivDiameter.nii.gz
dim		[3, 108, 83, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]

PAM50_200um_EquivDiameter14.nii.gz
dim		[3, 108, 83, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]

PAM50_200um_EquivDiameter48.nii.gz
dim		[3, 108, 83, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]

PAM50_200um_MVF.nii.gz
dim		[3, 108, 83, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]

PAM50_200um_Naxons.nii.gz
dim		[3, 108, 83, 205, 1, 1, 1, 1]
pixdim		[-1.0, 0.199074, 0.198795, 0.5, 0.0, 0.0, 0.0, 0.0]
```

The size is now 31M:

```console
valosek@macbook-pro:~/code/PAM50/histology_200x200x500um$ du -h                                           
 31M	.
```

<details><summary>orig PAM50_200um_Naxons.nii.gz</summary>

<img width="800" alt="Screenshot 2023-03-24 at 12 34 52 PM" src="https://user-images.githubusercontent.com/39456460/227586681-344c38cf-d4f5-42de-990a-19ecfa1cb427.png">

</details>

<details><summary>200 µm x 200 µm x 500 µm PAM50_200um_Naxons.nii.gz</summary>

<img width="800" alt="Screenshot 2023-03-24 at 12 34 46 PM" src="https://user-images.githubusercontent.com/39456460/227586725-f9d30fae-aba4-4c2f-bc7d-0420d212e24e.png">

</details>

**Comment by jcohenadad** [comment]
since you are doing a resampling anyway, how about using a 'round' 0.2 resolution (vs. 0.1991...)

**Comment by valosekj** [comment]
> since you are doing a resampling anyway, how about using a 'round' 0.2 resolution (vs. 0.1991...)

I indeed intended this using `sct_resample -i ${file} -mm 0.2x0.2x0.5 -x linear` (see the first command in https://github.com/spinalcordtoolbox/PAM50/issues/7#issuecomment-1483096525). But still, the resulting resolution is `0.199074x0.198795x0.5`.

**Comment by jcohenadad** [comment]
> I indeed intended this using sct_resample -i ${file} -mm 0.2x0.2x0.5 -x linear (see the first command in https://github.com/spinalcordtoolbox/PAM50/issues/7#issuecomment-1483096525). But still, the resulting resolution is 0.199074x0.198795x0.5.

interesting-- this is something we should raise as an SCT issue-- maybe related to some precision/rounding issues with the library used to do the resampling... we should clarify what the cause of this discrepancy is

**Comment by valosekj** [comment]
> > I indeed intended this using sct_resample -i ${file} -mm 0.2x0.2x0.5 -x linear (see the first command in [#7 (comment)](https://github.com/spinalcordtoolbox/PAM50/issues/7#issuecomment-1483096525)). But still, the resulting resolution is 0.199074x0.198795x0.5.
> 
> interesting-- this is something we should raise as an SCT issue-- maybe related to some precision/rounding issues with the library used to do the resampling... we should clarify what the cause of this discrepancy is
> 
> but regarding this project, if we want to move forward quickly, i'd say let's go with 0.199...

Documented in https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4077
